### PR TITLE
Fix/ios13 label headers

### LINKED ISSUE #41: iOS 13 new card style modal screens break doNotSee in NavigationContext
NavigationContext determines if you don't see an element by checking if it exists, but because iOS 13's new card modal presentation style for screen has a bit of the screen showing below, that screen (and all its elements) still exist.

It will take some thought on how to properly handle this. We can't use `isVisible(in)` as it currently works because that just checks if the frame of the device and the frame of the screen intersect, which they will, it's just that another screen is on top.

### LINKED ISSUE #42: iOS 13 UILabels are always seen as `staticText` even if they're headers
I've been trying to investigate this and it is seeming more and more like a bug in XCUI.

I can't even hide the label from XCUI by setting `isAccessibilityElement` to `false`, which suggest a bug to me.

### PR DESCRIPTION
**Pull request by KaneCheshire**
Fixes #42 and stops the card modal presentation style to temporarily fix #41

### CODE REVIEW

File: Example/TABTestKit/BiometricLoginViewController.swift [hunk 1]
```diff
@@ -26,10 +26,12 @@ final class BiometricLoginViewController: UIViewController {
     let canUseBiometrics = context.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error: .init(nilLiteral: ()))
     if canUseBiometrics {
       context.evaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, localizedReason: "Log in", reply: { [weak self] wasSuccessful, error in
-        if wasSuccessful {
-          self?.handleSuccessfulLogin()
-        } else {
-          self?.handleBiometricsFailed()
+        DispatchQueue.main.async {
```
Comment (KaneCheshire) [inline Example/TABTestKit/BiometricLoginViewController.swift]: This was crashing because the `reply` callback was being called on a background thread which crashes UIKit, so bumping onto the main queue here fixes that

File: TABTestKit/Classes/Extensions/Array+Safe.swift [hunk 2]
```diff
@@ -0,0 +1,22 @@
+//
+//  Array+Safe.swift
+//  Pods-TABTestKit_Example
```
Comment (KaneCheshire) [inline TABTestKit/Classes/Extensions/Array+Safe.swift]: Ugh this should be different, will fix

**Comment by KaneCheshire** [comment]
> God damn you, Apple. Good fixing, Kane. I take it we'll have to do some retraction of this work when they hopefully fix it all?

Yeah I was actually thinking we should create a placeholder issue to remind us to periodically check if this can be removed?

**Comment by zacoid55** [comment]
> > God damn you, Apple. Good fixing, Kane. I take it we'll have to do some retraction of this work when they hopefully fix it all?
> 
> Yeah I was actually thinking we should create a placeholder issue to remind us to periodically check if this can be removed?

Yeah good idea
